version: "3.7"
services:
  database:
    image: mysql:5.7
    volumes:
      - ./mysql/db/entrypoint:/docker-entrypoint-initdb.d/
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_DATABASE=feedback"
      - "MYSQL_ROOT_PASSWORD=geheim"
  feedback:
    build: .
    command: sh -c "apk add bash && bash ./wait-for-it.sh database:3306 --timeout=20 -- java -jar app.jar"
    ports:
      - "8080:8080"
