name: Java-CI

on:
  push:
    branches:
      - master
      - Integrationsbranch
  pull_request:
    branches:
      - master
      - Integrationsbranch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 13
      - name: Set up Database
        run: docker-compose up -d
      - name: Run Tests
        run: ./gradlew check
      - name: SpotBugs Main
        run: ./gradlew spotBugsMain
      - name: SpotBugs Test
        run: ./gradlew spotBugsTest
